#!/bin/bash
# To get the source from Maven first generate the POM file from Clojure
# for anything else see `lein help`
lein pom

# Then get the dependencies
mvn dependency:sources

# Or even make it possible to open the Java file in Eclipse
mvn eclipse:eclipse
